  RAILS_MODE = 0
  CAUSE_DIV_BY_ZERO = 0
  BAD_STRING_FOR_RAILS = 1
  MESSAGE_ONLY = 2
  FLAG_ONLY = 3
  ERROR_REPORTING = CAUSE_DIV_BY_ZERO
  NUM_ERR_DIGITS = 3
  MAX_LOOP = 10000
  MAX_TERMS = 50
  DESIRED_DIGITS = 34
  NUM_DIGITS = DESIRED_DIGITS + 4

